services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/var/www/app
      - ./conf/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-gd.ini
      - ./conf/php.ini-development:/usr/local/etc/php/php.ini-development
    depends_on:
      - db
    networks:
      - dev-network
    restart: always
    environment:
      - PHP_IDE_CONFIG="serverName=app"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  nginx:
    image: nginx:alpine
    volumes:
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/app
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - dev-network
    restart: always
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - dev-network

networks:
  dev-network:

volumes:
  db_data:
